### ISSUE TITLE
A fatal error occours on startup if no task exists 

### ISSUE THREAD

**Issue by aichingm** [scottkosty/vit#21] opened 2017-10-18 06:38 UTC
Vit crashes with: `Fatal error: default.command ("next") must print an "ID" column` if no task has been entered to the database. 

How to reproduce: 
1. empty your database: rm -rf ~/.task 
1. run vit
1. crash

Workaround: 
1. empty your database: `rm -rf ~/.task `
1. add a task with task `task add make some noise`
1. run vit
1. vit starts

I'm running vit from the commit d72d6e0 on Archlinux

**Comment by scottkosty** [comment] 2017-10-19 17:39
Thank you for your report! This is a big and embarrassing bug that from what I can tell has existed since the beginning of Vit. The bug is more general: if you run e.g. vit "blahblahblah", you get the same error. What should be expected by the user in both cases is that Vit opens displaying no tasks. I hope this gets fixed soon, but unfortunately I don't have much time these days for Vit.

**Comment by fdela** [comment] 2020-07-24 09:08
#40 is a duplicate of this bug. However the former has more information available, so this one can be closed

**Closed** 2020-07-24 13:41 UTC
